document.write("<section>");
document.write("<h2>Datos completos de la asignatura: </h2>");
document.write("<p>Curso actual: ");
document.write(asignatura.curso);
document.write("</p>");
document.write("<p>Alumna: ");
document.write(asignatura.alumna);
document.write("</p>");
document.write("<p>e-mail: ");
document.write(asignatura.email);
document.write("</p>");
document.write("</section>");